include:
  - local: "Abstractions/.gitlab-ci.yml"
  - local: "Services/.gitlab-ci.yml"

.publish_template:
    before_script:
      - "git clean -fdxq"
      - "dotnet tool install --global --prerelease sign"
      - "pwsh -f ./Abstractions/AbstractionsReplaceVersion.ps1"
      - "pwsh -f ./Services/ServicesReplaceVersion.ps1"
      - "az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID"
      - "az account set --subscription $AZURE_SUBSCRIPTION"
    after_script:
      - "az logout"

.build_template:
    before_script:
      - "git clean -fdxq"
      - "pwsh -f ./Abstractions/AbstractionsReplaceVersion.ps1"
      - "pwsh -f ./Services/ServicesReplaceVersion.ps1"

stages:
  - abstractions
  - abstractions-post
  - services
  - services-post

Increment Abstraction Build Counter:
  stage: abstractions-post
  tags:
    - linux
    - dotnet
  only:
    refs:
      - master
    changes:
      - Abstractions/**/*
  script:
    - "pwsh -f ./Abstractions/AbstractionsIncrementVersion.ps1"

Increment Services Build Counter:
  stage: services-post
  tags:
    - linux
    - dotnet
  only:
    refs:
      - master
    changes:
      - Services/**/*
  script:
    - "pwsh -f ./Services/ServicesIncrementVersion.ps1"
